# Generated by Django 4.1.3 on 2022-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_remove_ingredient_dishes_dish_ingredients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dishes",
            field=models.ManyToManyField(
                blank=True, related_name="ingredients", to="kitchen.dish"
            ),
        ),
    ]
